version: "3.8"
services:
  web1:
    container_name: web1
    build: .
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development





  web2:
    container_name: web2
    build: .
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development



  web3:
    container_name: web3
    build: .
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development


  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - 80:80
      - 5000:5000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./image:/nfsc/image/

