version: '3'

services:
  app:
    image: app:v1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8082:8080"
    networks:
      - webnet
networks:
  webnet: