version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - D:\develop\docker\kafka\data\docker.sock:/var/run/docker.sock